In [12]:
import torch
import torch.nn as nn

In [70]:
loss_function = nn.CrossEntropyLoss(weight = torch.tensor([1., 10.]), reduction = "none")

input = torch.randn(3, 2, requires_grad = True).softmax(dim=1)
print(input)
print()

target = torch.tensor([1, 0, 1])
print(target)
print()

loss = loss_function(input, target)

print(loss)

tensor([[0.0707, 0.9293],
        [0.1997, 0.8003],
        [0.1423, 0.8577]], grad_fn=<SoftmaxBackward>)

tensor([1, 0, 1])

tensor([3.5331, 1.0378, 3.9810], grad_fn=<NllLossBackward>)


In [77]:
loss_function = nn.CrossEntropyLoss(weight = torch.tensor([1., 10.]), reduction = "mean")

input = torch.randn(2, 3, 2, requires_grad = True).softmax(dim=1).view(6, 2)
print(input)
print()

target = torch.tensor([[0, 1, 0], [0, 1, 0]]).view(6)
print(target)
print()

loss = loss_function(input, target)

print(loss)

# Precision - recall kurver (tage arealet under) - AU PRC
# Kohens kappa.
# Confusion matrix.
# Adam/ASGD => Weight decay - L2 regularisation.

tensor([[0.1352, 0.2393],
        [0.3406, 0.4191],
        [0.5242, 0.3416],
        [0.0903, 0.1703],
        [0.7632, 0.0665],
        [0.1465, 0.7633]], grad_fn=<ViewBackward>)

tensor([0, 1, 0, 0, 1, 0])

tensor(0.8621, grad_fn=<NllLossBackward>)
