In [1]:
import neptune.new as neptune
import os
import torch.nn as nn
import torch
import torch.nn.functional as F
from torch.optim import SGD, Adam
from torch.utils.data import DataLoader, random_split
from torch.optim.lr_scheduler import LambdaLR
import torch.multiprocessing as mp
import numpy as np
import random
import math

import sys
sys.path.append("..") # adds higher directory to python modules path

from LoaderPACK.LSTM_net import LSTM_net

In [2]:
ind = torch.load(r"C:\Users\Marc\Desktop\Wierd output\ind.pt").to("cpu")

In [8]:
ind.shape

torch.Size([30, 1, 60000])

In [9]:
ind

tensor([[[-13.8992, -10.1994,  -3.7985,  ...,  -2.0160,  -5.0098, -12.1207]],

        [[  6.0457,  12.4945,  13.0280,  ...,   1.5957,   0.2744,   0.4520]],

        [[  9.0021,   7.7647,  44.1063,  ..., -16.4434,  -7.3825,   4.8528]],

        ...,

        [[ -4.1233,  10.0835,  14.9025,  ...,  14.4660, -11.6272,  -7.3358]],

        [[ 22.3071,  21.2660,  20.0025,  ...,   1.4527,   2.6604,   2.4418]],

        [[ -0.8942,   1.8171,   3.2695,  ...,  -3.2147,  -0.6232,   2.4024]]])

In [4]:
batch_size = 30
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)

In [5]:
out = model(ind)

In [6]:
out

tensor([[[0.5382, 0.5811, 0.6064,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4189, 0.3936,  ..., 0.3973, 0.4277, 0.4812]],

        [[0.5382, 0.5810, 0.6063,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4190, 0.3937,  ..., 0.3973, 0.4277, 0.4812]],

        [[0.5382, 0.5811, 0.6063,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4189, 0.3937,  ..., 0.3973, 0.4277, 0.4812]],

        ...,

        [[0.5382, 0.5810, 0.6063,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4190, 0.3937,  ..., 0.3973, 0.4277, 0.4812]],

        [[0.5382, 0.5810, 0.6063,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4190, 0.3937,  ..., 0.3973, 0.4277, 0.4812]],

        [[0.5382, 0.5810, 0.6063,  ..., 0.6027, 0.5723, 0.5188],
         [0.4618, 0.4190, 0.3937,  ..., 0.3973, 0.4277, 0.4812]]],
       grad_fn=<SoftmaxBackward0>)

In [7]:
out.shape

torch.Size([30, 2, 60000])

In [19]:
batch_size = 1
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)

In [20]:
ind[0].view(1, 1, -1)

tensor([[[-13.8992, -10.1994,  -3.7985,  ...,  -2.0160,  -5.0098, -12.1207]]])

In [21]:
model(ind[0].view(1, 1, -1))

tensor([[[0.2349, 0.2253, 0.2202,  ..., 0.2198, 0.2231, 0.2269],
         [0.7651, 0.7747, 0.7798,  ..., 0.7802, 0.7769, 0.7731]]],
       grad_fn=<SoftmaxBackward0>)

In [22]:
model(ind[1].view(1, 1, -1))

RuntimeError: bad allocation