In [1]:
import neptune.new as neptune
import os
import torch.nn as nn
import torch
import torch.nn.functional as F
from torch.optim import SGD, Adam
from torch.utils.data import DataLoader, random_split
from torch.optim.lr_scheduler import LambdaLR
import torch.multiprocessing as mp
import numpy as np
import random
import math

import sys
sys.path.append("..") # adds higher directory to python modules path

from LoaderPACK.LSTM_net import LSTM_net

In [2]:
ind = torch.load(r"C:\Users\Marc\Desktop\Wierd output\ind.pt").to("cpu")

In [3]:
ind.shape

torch.Size([10, 1, 60000])

In [4]:
ind

tensor([[[  5.7873,   2.8735,   4.3204,  ...,   1.8193,  -0.2992,  -0.6758]],

        [[  4.0954,   8.0991,   6.5922,  ...,  26.7045,  24.6322,  19.7239]],

        [[  7.6339,  10.7983,  11.2701,  ...,  -2.8396,  -6.4964,  -8.3752]],

        ...,

        [[ -7.6907,   0.3859,  22.7656,  ...,  -8.1175, -17.1491, -16.2881]],

        [[ 21.8641,  12.8339,  16.2406,  ...,  -4.5149,  -7.0672,  -8.2953]],

        [[ -0.3570,   0.5192,   1.3458,  ...,  -2.6831,  -9.9697,   5.9507]]])

In [5]:
batch_size = 10
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)

In [6]:
out = model(ind)

In [7]:
out

tensor([[[0.2642, 0.2583, 0.2553,  ..., 0.2486, 0.2481, 0.2472],
         [0.7358, 0.7417, 0.7447,  ..., 0.7514, 0.7519, 0.7528]],

        [[0.2647, 0.2595, 0.2563,  ..., 0.2526, 0.2525, 0.2508],
         [0.7353, 0.7405, 0.7437,  ..., 0.7474, 0.7475, 0.7492]],

        [[0.2655, 0.2604, 0.2574,  ..., 0.2460, 0.2458, 0.2455],
         [0.7345, 0.7396, 0.7426,  ..., 0.7540, 0.7542, 0.7545]],

        ...,

        [[0.2610, 0.2569, 0.2553,  ..., 0.2470, 0.2465, 0.2461],
         [0.7390, 0.7431, 0.7447,  ..., 0.7530, 0.7535, 0.7539]],

        [[0.2652, 0.2602, 0.2572,  ..., 0.2461, 0.2462, 0.2458],
         [0.7348, 0.7398, 0.7428,  ..., 0.7539, 0.7538, 0.7542]],

        [[0.2618, 0.2563, 0.2536,  ..., 0.2472, 0.2488, 0.2498],
         [0.7382, 0.7437, 0.7464,  ..., 0.7528, 0.7512, 0.7502]]],
       grad_fn=<SoftmaxBackward0>)

In [8]:
out.shape

torch.Size([10, 2, 60000])

In [9]:
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[-0.3592],
        [ 0.1598],
        [-0.0487],
        [ 0.2768],
        [-0.1013],
        [-0.0279],
        [ 0.3813],
        [ 0.3821],
        [ 0.0834],
        [-0.1654],
        [-0.0716],
        [ 0.0068],
        [ 0.2304],
        [ 0.2973],
        [ 0.1545],
        [ 0.4453],
        [-0.1392],
        [-0.0912],
        [-0.2889],
        [ 0.2885]], requires_grad=True)
Parameter containing:
tensor([[-0.2917],
        [-0.3682],
        [ 0.0993],
        [-0.3259],
        [ 0.4269],
        [-0.2879],
        [ 0.2091],
        [ 0.3414],
        [ 0.0187],
        [-0.3138],
        [-0.4030],
        [ 0.0831],
        [ 0.4470],
        [-0.2244],
        [ 0.3867],
        [-0.1484],
        [ 0.3284],
        [ 0.1145],
        [ 0.1456],
        [-0.0074]], requires_grad=True)
Parameter containing:
tensor([ 0.3175, -0.4095, -0.0558, -0.1720, -0.0978, -0.2054,  0.0591,  0.3505,
         0.1288, -0.0831, -0.2292,  0.2767,  0.3148,

In [10]:
x = torch.load(f"C:/Users/Marc/Desktop/network/network_LSTM-510.pt", map_location='cpu')
x

OrderedDict([('lstm.weight_ih_l0',
              tensor([[ 9.5604e-01],
                      [-2.7282e-01],
                      [-6.0851e-01],
                      [-7.6993e-01],
                      [ 1.1170e+00],
                      [ 9.4927e-01],
                      [ 1.4081e+00],
                      [ 7.1743e-01],
                      [ 2.6803e-01],
                      [ 8.7604e-01],
                      [-1.5671e-03],
                      [ 9.5805e-01],
                      [ 1.7373e+00],
                      [ 5.7856e-01],
                      [ 1.9273e-01],
                      [-3.7190e-01],
                      [ 1.2352e+00],
                      [ 1.0384e+00],
                      [-7.7336e-01],
                      [-3.9639e-01]])),
             ('lstm.weight_hh_l0',
              tensor([[-0.0127],
                      [-0.5819],
                      [ 0.4052],
                      [-0.2645],
                      [ 0.5958],
                      

In [14]:
batch_size = 10
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)
x = torch.load(f"C:/Users/Marc/Desktop/network/network_LSTM-510.pt", map_location='cpu')
model.load_state_dict(x)
model.to(device)

LSTM_net(
  (lstm): LSTM(1, 5, proj_size=1, num_layers=2, batch_first=True, bidirectional=True)
  (soft): Softmax(dim=1)
)

In [15]:
out = model(ind)

In [16]:
out

tensor([[[0.2765, 0.3258, 0.5128,  ..., 0.7003, 0.4630, 0.0561],
         [0.7235, 0.6742, 0.4872,  ..., 0.2997, 0.5370, 0.9439]],

        [[0.2805, 0.3000, 0.3256,  ..., 0.5105, 0.5104, 0.5063],
         [0.7195, 0.7000, 0.6744,  ..., 0.4895, 0.4896, 0.4937]],

        [[0.2710, 0.2571, 0.2620,  ..., 0.0217, 0.0906, 0.1333],
         [0.7290, 0.7429, 0.7380,  ..., 0.9783, 0.9094, 0.8667]],

        ...,

        [[0.2699, 0.2731, 0.1088,  ..., 0.1321, 0.1606, 0.1901],
         [0.7301, 0.7269, 0.8912,  ..., 0.8679, 0.8394, 0.8099]],

        [[0.2090, 0.2195, 0.2205,  ..., 0.0412, 0.0566, 0.0761],
         [0.7910, 0.7805, 0.7795,  ..., 0.9588, 0.9434, 0.9239]],

        [[0.2820, 0.3570, 0.6185,  ..., 0.2710, 0.2696, 0.0930],
         [0.7180, 0.6430, 0.3815,  ..., 0.7290, 0.7304, 0.9070]]],
       grad_fn=<SoftmaxBackward0>)

In [17]:
batch_size = 1
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)
x = torch.load(f"C:/Users/Marc/Desktop/network/network_LSTM-510.pt", map_location='cpu')
model.load_state_dict(x)
model.to(device)

LSTM_net(
  (lstm): LSTM(1, 5, proj_size=1, num_layers=2, batch_first=True, bidirectional=True)
  (soft): Softmax(dim=1)
)

In [18]:
model(ind[0].view(1, 1, -1))

tensor([[[0.2765, 0.3258, 0.5128,  ..., 0.7003, 0.4630, 0.0561],
         [0.7235, 0.6742, 0.4872,  ..., 0.2997, 0.5370, 0.9439]]],
       grad_fn=<SoftmaxBackward0>)

In [19]:
model(ind[9].view(1, 1, -1))

tensor([[[0.2820, 0.3570, 0.6185,  ..., 0.2710, 0.2696, 0.0930],
         [0.7180, 0.6430, 0.3815,  ..., 0.7290, 0.7304, 0.9070]]],
       grad_fn=<SoftmaxBackward0>)

In [13]:
batch_size = 1
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)

x = torch.load(r"C:\Users\Marc\Desktop\Wierd output\net.pt", map_location='cpu')
model.load_state_dict(x)
model.to(device)

RuntimeError: Error(s) in loading state_dict for LSTM_net:
	Unexpected key(s) in state_dict: "lstm.weight_ih_l2", "lstm.weight_hh_l2", "lstm.bias_ih_l2", "lstm.bias_hh_l2", "lstm.weight_hr_l2", "lstm.weight_ih_l2_reverse", "lstm.weight_hh_l2_reverse", "lstm.bias_ih_l2_reverse", "lstm.bias_hh_l2_reverse", "lstm.weight_hr_l2_reverse", "lstm.weight_ih_l3", "lstm.weight_hh_l3", "lstm.bias_ih_l3", "lstm.bias_hh_l3", "lstm.weight_hr_l3", "lstm.weight_ih_l3_reverse", "lstm.weight_hh_l3_reverse", "lstm.bias_ih_l3_reverse", "lstm.bias_hh_l3_reverse", "lstm.weight_hr_l3_reverse", "lstm.weight_ih_l4", "lstm.weight_hh_l4", "lstm.bias_ih_l4", "lstm.bias_hh_l4", "lstm.weight_hr_l4", "lstm.weight_ih_l4_reverse", "lstm.weight_hh_l4_reverse", "lstm.bias_ih_l4_reverse", "lstm.bias_hh_l4_reverse", "lstm.weight_hr_l4_reverse". 
	size mismatch for lstm.weight_ih_l0: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.weight_hh_l0: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.bias_ih_l0: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.bias_hh_l0: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.weight_hr_l0: copying a param with shape torch.Size([1, 2]) from checkpoint, the shape in current model is torch.Size([1, 5]).
	size mismatch for lstm.weight_ih_l0_reverse: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.weight_hh_l0_reverse: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.bias_ih_l0_reverse: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.bias_hh_l0_reverse: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.weight_hr_l0_reverse: copying a param with shape torch.Size([1, 2]) from checkpoint, the shape in current model is torch.Size([1, 5]).
	size mismatch for lstm.weight_ih_l1: copying a param with shape torch.Size([8, 2]) from checkpoint, the shape in current model is torch.Size([20, 2]).
	size mismatch for lstm.weight_hh_l1: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.bias_ih_l1: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.bias_hh_l1: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.weight_hr_l1: copying a param with shape torch.Size([1, 2]) from checkpoint, the shape in current model is torch.Size([1, 5]).
	size mismatch for lstm.weight_ih_l1_reverse: copying a param with shape torch.Size([8, 2]) from checkpoint, the shape in current model is torch.Size([20, 2]).
	size mismatch for lstm.weight_hh_l1_reverse: copying a param with shape torch.Size([8, 1]) from checkpoint, the shape in current model is torch.Size([20, 1]).
	size mismatch for lstm.bias_ih_l1_reverse: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.bias_hh_l1_reverse: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([20]).
	size mismatch for lstm.weight_hr_l1_reverse: copying a param with shape torch.Size([1, 2]) from checkpoint, the shape in current model is torch.Size([1, 5]).

In [ ]:
out = model(ind[0].view(1, 1, -1))

In [ ]:
out

In [ ]:
for i in model.parameters():
    print(i)

In [ ]:
batch_size = 1
device = "cpu"

model = LSTM_net(batch_size=batch_size, device=device).to(device)

In [ ]:
ind[0].view(1, 1, -1)

In [ ]:
model(ind[0].view(1, 1, -1))

In [ ]:
model(ind[1].view(1, 1, -1))