In [2]:
import torch
import torch.nn as nn

In [70]:
loss_function = nn.CrossEntropyLoss(weight = torch.tensor([1., 10.]), reduction = "none")

input = torch.randn(3, 2, requires_grad = True).softmax(dim=1)
print(input)
print()

target = torch.tensor([1, 0, 1])
print(target)
print()

loss = loss_function(input, target)

print(loss)

tensor([[0.0707, 0.9293],
        [0.1997, 0.8003],
        [0.1423, 0.8577]], grad_fn=<SoftmaxBackward>)

tensor([1, 0, 1])

tensor([3.5331, 1.0378, 3.9810], grad_fn=<NllLossBackward>)


In [1]:
loss_function = nn.CrossEntropyLoss(weight = torch.tensor([1., 10.]), reduction = "mean")

input = torch.randn(2, 3, 2, requires_grad = True).softmax(dim=1).view(6, 2)
print(input)
print()

target = torch.tensor([[0, 1, 0], [0, 1, 0]]).view(6)
print(target)
print()

loss = loss_function(input, target)

print(loss)

# Precision - recall kurver (tage arealet under) - AU PRC
# Kohens kappa.
# Confusion matrix.
# Adam/ASGD => Weight decay - L2 regularisation.

NameError: name 'nn' is not defined

In [82]:
loss_function = nn.CrossEntropyLoss(weight = torch.tensor([1., 10.]), reduction = "mean")

input = torch.randn(10, 2, 75000, requires_grad = True).softmax(dim=1)
print(input.transpose(1, 2).reshape(-1, 2).shape)
print(type(input))
print()

target = torch.randint(0, 2, (75000*10,))
print(target.shape)
print()

loss = loss_function(input.transpose(1, 2).reshape(-1, 2), target)
print(loss)

torch.Size([750000, 2])
<class 'torch.Tensor'>

torch.Size([750000])

tensor(0.7268, grad_fn=<NllLossBackward0>)


In [84]:
target.dtype

torch.int64